### ISSUE TITLE
add built-in screenshot and annotations

### ISSUE THREAD

**Issue by mark-hahn** [lee-dohm/bug-report#28]
Check out https://chrome.google.com/webstore/detail/awesome-screenshot-captur/alelhddbbhepgpmgidjdcjakblofbmce

It would be awesome is a user could click a button in bug-report, get a screenshot of the entire window, annotate it, and add it to the markdown.

I could copy the functionality in the extension I referred to above.  It must work well because it has 1.4 million users.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/bug-report), this package is no longer maintained and is deprecated. If you want to report a bug in Atom itself, please check out [Atom's support resources](https://github.com/atom/atom/SUPPORT.md). If you're looking for a new package to report bugs with, we recommend that people use the [town-crier package](https://github.com/atom/town-crier) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
