### ISSUE TITLE
Support multiple inputs from other sources

### ISSUE THREAD

**Issue by mark-hahn** [lee-dohm/bug-report#30]
There is a good chance that other packages are going to feed data to bug-report.  If each created a new bug-report, as error-status does now, then multiple reports would be created.  This would requite manually merging the reports which is awkward at best.

I propose that when external data comes in we check  for an already open bug report tab item and just update it if it exists.  This would be easy to do.

It might even be useful with one source like error-status.  You could leave the bug-report open and create different errors to go in the one report.  I know this is kind of a stretch for a use case.  (grin)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/bug-report), this package is no longer maintained and is deprecated. If you want to report a bug in Atom itself, please check out [Atom's support resources](https://github.com/atom/atom/SUPPORT.md). If you're looking for a new package to report bugs with, we recommend that people use the [town-crier package](https://github.com/atom/town-crier) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
