### ISSUE TITLE
add chrome version

### ISSUE THREAD

**Issue by mark-hahn** [lee-dohm/bug-report#31]
Once again I couldn't find a version and went to bug-report with no luck.

BTW, bug-report is turning into a useful tool even without bugs.  So far I use it a lot but to get versions.  Maybe I'll spin off a second package that simply shows the versions.

Also BTW, no one seems to be using it.  I haven't seen a report so far, have you?  I hope the concept isn't flawed.  People don't seem to report bugs.  They just bitch that 'xxx doesn't work'.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/bug-report), this package is no longer maintained and is deprecated. If you want to report a bug in Atom itself, please check out [Atom's support resources](https://github.com/atom/atom/SUPPORT.md). If you're looking for a new package to report bugs with, we recommend that people use the [town-crier package](https://github.com/atom/town-crier) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
