### ISSUE TITLE
Add button to post to Discuss

### ISSUE THREAD

**Issue by lee-dohm** [lee-dohm/bug-report#4]

**Comment by batjko** [comment]
I wonder if this double posting would be wise. Opening a github issue should be the central and preferred way of reporting problems and tracking effort against them?

Imagine people constantly posting their issues as Discuss topics as well, just because they hope it gets fixed faster that way. Believe me, if you give them that option they will make use of it extensively.

**Comment by lee-dohm** [comment]
That's a good point. I was thinking of it as an either/or proposition.

**Comment by mark-hahn** [comment]
> Opening a github issue should be the central and preferred way of
reporting problems

That isn't obvious to users.  There are many bugs reported on discuss.  And
a lot of the time users don't know if it is a bug or not.

**Comment by batjko** [comment]
Yes, true. But then this distinction should probably be communicated in a
useful way. Instead of creating forum threads on Discuss (where there's no
guarantee of support by the core team or anyone really), Github issues are
the supported... support.

But of course people may simply have questions or ideas about the report at
hand that they want to bring up on Discuss, so maybe the second option
could be named something like "Post *about* this on Discuss", as an
alternative to "Report issue on Github"?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/bug-report), this package is no longer maintained and is deprecated. If you want to report a bug in Atom itself, please check out [Atom's support resources](https://github.com/atom/atom/SUPPORT.md). If you're looking for a new package to report bugs with, we recommend that people use the [town-crier package](https://github.com/atom/town-crier) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
