### ISSUE TITLE
error-status stack trace didn't appear

### ISSUE THREAD

**Issue by mark-hahn** [lee-dohm/bug-report#41]
I got an error (https://github.com/atom/atom/issues/4397#event-202990058).  `error-status` showed a stack trace.  I clicked on `report` in the `error-status` panel.  The bug-report did not have anything from `error-status`.

I obviously don't know if this is an `error-status` problem or a `bug-report` problem.  More testing is needed.

Bug-report v0.5.3
- **Atom:**       0.152.0
- **Atom-Shell:** 0.19.4
- **OS:**         Microsoft Windows 8.1 Pro with Media Center
- **Misc**
  - apm  0.111.0
  - npm  1.4.4
  - node 0.10.33
  - python 2.7.8
  - git 1.7.11.msysgit.1
  - visual studio 2013

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/bug-report), this package is no longer maintained and is deprecated. If you want to report a bug in Atom itself, please check out [Atom's support resources](https://github.com/atom/atom/SUPPORT.md). If you're looking for a new package to report bugs with, we recommend that people use the [town-crier package](https://github.com/atom/town-crier) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
