### ISSUE TITLE
allow user to see existing issues

### ISSUE THREAD

**Issue by mark-hahn** [lee-dohm/bug-report#43]
When I posted an issue right now it turned out to be a duplicate of the one just before it.  There is no way to check for duplicates before posting.

I'm not sure how to fix this but it would be a really useful feature.  The option to see issues should be given before they go to the trouble of preparing the report.

One challenging idea is to show possible duplicates chosen by an intelligent algorithm.  In discourse I have noticed that when typing in a comment it shows a very intelligent list of possible issues.  I wonder is discourse is open-source?

Letting the see the list before preparing the report and having an intelligent list is a conflict.  Maybe it should show it while typing like discourse.  This needs a lot of thought.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/bug-report), this package is no longer maintained and is deprecated. If you want to report a bug in Atom itself, please check out [Atom's support resources](https://github.com/atom/atom/SUPPORT.md). If you're looking for a new package to report bugs with, we recommend that people use the [town-crier package](https://github.com/atom/town-crier) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
