### ISSUE TITLE
add electron version and chrome version

### ISSUE THREAD

**Issue by lemongrassnginger** [lee-dohm/bug-report#61]
Swap the atom shell entry for electron version and add a chrome version (both are missing from the bug-report). 

I'd be happy to help implement but I'd need a couple of pointers to get me started, am relatively new to atom package development.

`atom --version` provides something like the following: 

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/lee-dohm/bug-report), this package is no longer maintained and is deprecated. If you want to report a bug in Atom itself, please check out [Atom's support resources](https://github.com/atom/atom/SUPPORT.md). If you're looking for a new package to report bugs with, we recommend that people use the [town-crier package](https://github.com/atom/town-crier) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
